### ISSUE TITLE
Correction description du projet

### ISSUE THREAD

**Issue by dam09fr** [RaspbianFrance/RaspiSMS#10]
Quelques fautes sur la description du projet : *"RaspiSMS est un système de gestion et d'**envoie** de SMS par ordinateur, initialement conçu **poiyr** les Raspberry **P**"*
Version corrigée : *"RaspiSMS est un système de gestion et d'envoi de SMS par ordinateur, initialement conçu pour les Raspberry Pi"*
Autre petite suggestion, ajouter l'URL : *"http://raspisms.raspbian-france.fr/"*

**Comment by RaspbianFrance** [comment]
Merci, nous corrigeons tout de suite :)
