### ISSUE TITLE
Raspberry (raspbian stretch) raspisms install MySQL errors

### ISSUE THREAD

**Issue by zicmama** [RaspbianFrance/raspisms#101]
Je viens de lancer l'installation du paquet raspisms-2.0.1.deb

Il y a une erreur lors de la création de la base MySQL:

> Le fichier de configuration /etc/gammu-smsdrcrc n'a pas pu être généré. Vous devrez le configurer à la main.
> La base de données de RaspiSMS va être déployée.
> Création de l'utilisateur MySQL ''raspisms''
> raspisms password = password
> L'utilisateur MySQL 'raspisms' a bien été créé. Vous pouvez retrouver son mot de passe dans le fichier '/var/www/html/RaspiSMS/mvc/constants.php'.
> ERROR 1071 (42000) at line 123: Specified key was too long; max key length is 767 bytes
>  Une erreur est survenue lors de la création de la base de données, effectuez cette création à la main avec la commande 'mysql -u raspisms -ppassword < /var/www/html/RaspiSMS/createDatabase.sql'
> 

Enfin voici ce que je trouve dans MySQL (# mysql -u root)
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| raspisms           |
+--------------------+
4 rows in set (0.00 sec)

MariaDB [(none)]> use raspisms;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [raspisms]> show tables;
+---------------------+
| Tables_in_raspisms  |
+---------------------+
| commands            |
| contacts            |
| events              |
| groups              |
| groups_contacts     |
| receiveds           |
| scheduleds          |
| scheduleds_contacts |
| scheduleds_groups   |
| scheduleds_numbers  |
| sendeds             |
| settings            |
+---------------------+
12 rows in set (0.00 sec)

Le problème vient de la création de la table users
ERROR 1146 (42S02) at line 1: Table 'raspisms.users' doesn't exist
 Impossible de créer le compte administrateur pour raspisms. Vous devrez le créer vous même avec la commande MySQL INSERT INTO users(email, password, admin) VALUES('xxxxxt@yyyy.com', SHA1('adminpwd'), 1)

**Comment by jhillairet** [comment]
Il y'avait une erreur dans le fichier de définition de la base de donnée : cf le commit e585647583a49036bf00fd60983cd20259186a8a. Il faut corriger la valeur 255 en 191 et réessayer.

**Comment by zicmama** [comment]
J'ai téléchargé le deb ici
https://raspisms.raspbian-france.fr/download/raspisms-2.0.1.deb

**Comment by zicmama** [comment]
Après correction de la creation de la base MySQL, quand j'accède à RaspiSMS, je me trouve confronté à l'erreur.

Erreur : SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost'

**Comment by zicmama** [comment]
Dans "/var/www/html/RaspiSMS/mvc/constants.php", il faut changer le user (par défaut root / sans mot de passe) en "raspisms / password"

Le scprit de confiugation informe de ce paramètre à l'installation (création de la base MySQL), mais le fichier constants.php n'est pas conforme.. 

```
La base de données de RaspiSMS va être déployée.
Création de l'utilisateur MySQL ''raspisms''
raspisms password = password
L'utilisateur MySQL 'raspisms' a bien été créé. Vous pouvez retrouver son mot de passe dans le fichier '/var/www/html/RaspiSMS/mvc/constants.php'.


```

**Comment by jhillairet** [comment]
Effectivement, j'ai eu le même souci, c'est bien de le documenter (ce que je n'ai pas fait).  

Attention : si on lance plusieurs fois de suite le script d'installation, cela accumule les lignes dans le crontab. Il faut alors enlever les doublons dans le crontab (`sudo crontab -e`) sinon les SMS seront envoyés en double ou plus.
