### ISSUE TITLE
 Nombre de chiffres dans le pays Le Brésil est incorrect

### ISSUE THREAD

**Issue by spaschoalick** [RaspbianFrance/raspisms#106]
Tout d'abord, je voudrais remercier les développeurs de RaspiSMS.

Je l'ai installé et j'ai fini par faire la traduction portugaise du Brésil.
Je suis impatient de l'utiliser dans l'entreprise pour laquelle je travaille.

La seule difficulté que j'ai rencontrée jusqu'ici est que le nombre de chiffres dans le contact n'est pas correct.

Exemple d'un numéro de portable au Brésil +55 (11) 99551-2020

Pourriez-vous me dire où je corrige ce problème?

Merci!

**Comment by thomasbonsirven** [comment]
Bonsoir,

Franchement, je ne sais pas.
mais je vais essayer de me pencher sur le sujet.
