### ISSUE TITLE
Changer expéditeur

### ISSUE THREAD

**Issue by tartreau** [RaspbianFrance/raspisms#108]
Bonjour, je voudrais savoir si dans RaspiSMS il était possible d'afficher un nom lors de la réception du SMS plutôt que le numéro. 
Si oui ou faire le changement ? Dans RaspiSMS ou il faut fouiller dans des fichiers ?

**Comment by thomasbonsirven** [comment]
Bonjour

Effectivement, je cherche aussi la solution.
Il n'y a pas de possibilité dans linterface. ( Du moins de ce que j'ai vu ).

Je cherche donc dans les fichiers.

Je te tiens au jus.

**Comment by RaspbianFrance** [comment]
Salut, non désolé ce n'est pas possible.
En fait le changement de nom lors de l'affichage du numéro est une sorte de
trucage qui est effectué directement par les opérateurs téléphoniques.
La seule solution serait donc de trouver une carte sim chez un opérateur
offrant cette possibilité.

Le sam. 28 avr. 2018 09:02, thomasbonsirven <notifications@github.com> a
écrit :

**Comment by tartreau** [comment]
D'accord, est-ce que vous connaissez la procédure à suivre pour cela ?

**Comment by RaspbianFrance** [comment]
Salut, désolé non pas du tout.
Comme c'est géré par l'opérateur, je présume qu'il faudrait leur demander
directement. Mais il doit s'agir de contrat spéciaux de type commerciaux.
Le plus simple serait peut-être de contacter le support des grands
opérateurs (par twitter par exemple) pour leur demander.

2018-04-30 10:54 GMT+02:00 tartreau <notifications@github.com>:

**Comment by tartreau** [comment]
Très bien merci !

**Comment by thomasbonsirven** [comment]
Bonjour,

Pour information, 

Free ne fait pas ce genre de service.

Il y a Orange devis à 99€ht par mois ( tres chere )
SFR avec un devis à 79€/mois ht
Bouygues Pro ( 49€/mois TTC ) 
Entreprise (79€/mois HT )

Services only sms sans aucune limitation, avec négociation ( par confirmé pour Bouygues Pro )

Il en ressort que cela reste un service pour les entreprises, ou association ;)
