### ISSUE TITLE
Comment mettre à jour RaspiSMS 

### ISSUE THREAD

**Issue by bash2121** [RaspbianFrance/raspisms#110]
Bonjour,

J'ai installé la version RaspiSMS en version 2.0 car j'ai eu beaucoup de mal pour installer la version deb 2.0.1. Je n'ai pas réussi à l'installer, à chaque fois des problème SQL ou des pages blanches.
J'ai donc choisi d'installer le package 2.0.
Tout fonctionne très bien.
Sauf que j'avais besoin de l'API groups, et je vois qu'il y a un commit sur github.

Comment puis-je faire pour mettre à jour de la maniere la plus simple ?
cdlt.

**Comment by thomasbonsirven** [comment]
Bonjour,

réupere le deb ici et une mise a jours avec ce fichier deb : 
https://github.com/RaspbianFrance/raspisms-deb-package

Je te conseil de prendre tous les fichiers :)

`wget https://github.com/RaspbianFrance/raspisms-deb-package/archive/master.zip`

ensuite un unzip : 

`unzip master.zip`

puis tu installe : 

`cd master
dpkg -i raspisms.deb`

Dit le nous si cela fonctionne ou pas :)
