### ISSUE TITLE
message length limited to 24 characters

### ISSUE THREAD

**Issue by clodion** [RaspbianFrance/raspisms#112]
Hello everybody.

When I send sms via http with this command : http://123.123.123.123:81/RaspiSMS/smsAPI/?email=admin@example.fr&password=admin&numbers=0123456789&text=texte_to_write, whatever the text lentgh, it works. But when I use the curl command, the messages works only when it is under 124 chars length. 

any idea ?

**Comment by LaurentThiol** [comment]
please control your gammu-smsd with "service gammu-smsd status"
