### ISSUE TITLE
Reveived dir path is invalid in parseSMS.sh

### ISSUE THREAD

**Issue by nico2am** [RaspbianFrance/raspisms#121]
Hi, 

I've installed RaspiSMS, and in parseSMS.sh the path of receiveds dir is : 
/var/www/RaspiSMS/receiveds/"$date".txt
but now apache put file in /var/www/html/RaspiSMS/receiveds/"$date".txt
/html/ is missing.

**Comment by vincent1890** [comment]
Hi 

OsaAjani committed on 23 Jan 2018 already fixed on git but not in the official .deb

Bye
