### ISSUE TITLE
Envoi possible en ssh via gammu mais pas via l'interface Raspisms

### ISSUE THREAD

**Issue by waazdakka** [RaspbianFrance/raspisms#123]
Bonjour !

Après avoir installé avec succès Raspisms sur un RPi 3B+ sur Raspbian stretch lite, avec une clef Huawei E220 , j'ai tenté l'envoi d'un sms (en suivant scrupuleusement le tuto ici : https://raspbian-france.fr/raspisms-raspberry-pi-sms-internet), j'ai testé celui-ci tout d'abord directement via gammu, avec un
`echo "test" | sudo gammu sendsms TEXT XXXXXXXXXX`.
La commande fonctionne très bien et je reçois bien les SMS (pas encore testé la réception sur la clef...). En revanche, directement depuis l'interface web, en programmant un sms. Celui-ci apparaît comme parti depuis RaspiSMS, mais la cible ne reçoit rien.

J'imagine qu'il doit manquer un élément de configuration quelque part que j'ai omis de modifier ? 

Mon fichier de config de gammu
`
# SMSD configuration, see gammu-smsdrc(5)
[smsd]
service = files
logfile = syslog
# Increase for debugging information
debuglevel = 0
RunOnReceive = /var/www/html/RaspiSMS/parseSMS.sh
# Paths where messages are stored
inboxpath = /var/spool/gammu/inbox/
outboxpath = /var/spool/gammu/outbox/
sentsmspath = /var/spool/gammu/sent/
errorsmspath = /var/spool/gammu/error/
`

Merci de votre aide !!

**Comment by stevecohenfr** [comment]
Salut, as-tu bien ajouté ces 2 lignes à ta crontab root ?

    * * * * * cd /var/www/html/RaspiSMS && /var/www/html/RaspiSMS/console.php -c parseReceivedSMS
    * * * * * cd /var/www/html/RaspiSMS && /var/www/html/RaspiSMS/console.php -c sendScheduleds
