### ISSUE TITLE
Commandes et Python

### ISSUE THREAD

**Issue by JP-24** [RaspbianFrance/raspisms#124]
Bonjour à tous,
j'ai installé RaspiSMS sans trop de difficultés en utilisant la version 2.0.1 ainsi qu'ici pour finaliser quelques points ("Synthèse des bugs 2.0.1").
Je peux envoyer/recevoir sans problème.
J'ai dans l'idée de déclencher sur commande un script en python mais c'est là que ça bloque.
Le Log des SMS reçus m'indique bien qu'il exécute une commande mais rien ne se passe (j'ouvre un fichier et j'y écris les paramètres passés).
Le script fonctionne en ligne de commande; du coup je me suis dit que c'était la syntaxe de la commande qui n'était pas la bonne. J'ai essayé plein de chose : rien.
Si j'utilise un script Bash, c'est bon...
Bref, si quelqu'un pouvait me dire comment écrire la commande dans l'interface Web de RaspiSMS, je pourrai continuer d'avancer.
Peut-être qu'il faut faire quelque chose dans l'entête du script Python. Bref je sèche.
Merci à tous et toutes
JP

**Comment by stevecohenfr** [comment]
Salut, dans mon cas en nodejs j'ai du préciser le binaire à utiliser et non uniquement le chemin du script :

    node scripts/speak/index.js

En espérant que ça vous aide
