### ISSUE TITLE
réception et autres petits tracas

### ISSUE THREAD

**Issue by mwagaboche** [RaspbianFrance/raspisms#125]
Bonjour,
je me suis penché sur ce projet depuis quelques temps dans le but d'équiper une association d'un dispositif fonctionnel et peu coûteux.
Malheureusement je reste bloqué sur la réception des SMS. J'ai lu les autres messages et ai fait le tour de plusieurs forums.
j'ai donc suivi de A à Z (ou du moins il me semble) les étapes du post sur la correction des bugs de la v2.0.1

Je viens aussi de passer une après-midi à relire le code et je commence à avoir mal à la tête.

Dans /var/spool/gammu/inbox  je retrouve certains (mais pas tous) des messages que j'essaye de retrouver et des "accusésderéception"? (fichiers contenant 'Delivered').
[mais dans l'interface web le statut des messages est "inconnu"]

Je ne retrouve rien dans ma base de données ou dans le dossiers /var/www/html/RaspiSMS/receiveds ( à l'exception du .to-keep bien sur).

crontab OK

en retraçant l'exécution de la commande je suis le chemin du console.php au internalconsole.php. j'ai retrouvé la variable PWD_RECEIVEDS dans constant.php et si ma compréhension est correcte j'en conclu que ce mécanisme prend les messages présents dans le dossier /var/www/html/RaspiSMS/receiveds 

j'ai donc cherché à savoir comment le dossier est rempli. Sauf erreur cela se fait par le script parseSMS.sh

en l'exécutant manuellement il me retourne 
`seq: opÃ©rande manquant`

En effet la ligne concernée est `for i in `seq $SMS_MESSAGES` ; do` et je ne trouve pas (pour le moment) la déclaration de cette variable.

voilà

Je sais que je suis désordonné et que j'écris beaucoup mais j'espère qu'avec ces informations quelqu'un pourra me donner la solution miracle ( avec un peu de chance et si j'ai manqué un truc) ou m'aider à remonter le fil jusqu'au problème.
Mais bon comme j'ai l'impression que tout le monde arrive à le faire marcher j'ai l'impression que je nage dans des problèmes illusoires.

je reviendrais poster si j'avance, en espérant que ce ne soit pas un monologue. =)

Et merci d'avance pour tous ceux qui pourront me consacrer un peu de temps ( sans obligation de résultat bien entendu ;)  )

**Comment by leknoppix** [comment]
J'ai eu pas mal de soucis aussi pour la première installation. J'ai le script fonctionne chez moi, depuis 3 ans.

J'étais passé par ce topic => https://github.com/RaspbianFrance/RaspiSMS/issues/115 dis moi si cela fonctionne où pas.
