### ISSUE TITLE
Contribution au projet 

### ISSUE THREAD

**Issue by stevecohenfr** [RaspbianFrance/raspisms#126]
Bonjour, le projet est-il toujours en développement ? Je ne vois plus d'activité sur master depuis 1 an et que dev depuis 4 mois.

Est-il possible de contribuer via des merge request ? Quelle procédure ?

Merci énormément pour ce projet :)

**Comment by leknoppix** [comment]
Bonjour

Ayant été en contact avec les dev, rien de t'empêche de faire un fork, faire tes modifs et les proposer en pull requests. Au moins de cette manière, si c'est pas traité ou pas accepté (https://github.com/RaspbianFrance/RaspiSMS/pulls), les gens peuvent consulter ton fork.

**Comment by stevecohenfr** [comment]
Salut ! Merci de ta réponse je vais faire ça.

Steve
