### ISSUE TITLE
Interface RAspisms le statut des messages reste en Inconnu

### ISSUE THREAD

**Issue by Ulrick17** [RaspbianFrance/raspisms#141]
Bonjour 

J'ai pu installer raspisms sur un raspberry et j'arrive à envoyer des messages en CMD ou via l'interface.

Sauf que via l'interface les messages sont bien recus mais leur statut reste en inconnu 

Avez-vous une idée

**Comment by ferrader** [comment]
Salut, 
cela peut dépendre de ton opérateur. tu as quoi comme configuration?
Bonne journée,
