### ISSUE TITLE
envoyer email par le SMTP de Gmail

### ISSUE THREAD

**Issue by tparvais** [RaspbianFrance/raspisms#142]
Bonjour
Comment puis-je configurer le module Mail de PHP intégré dans l'outil pour utiliser le serveur SMTP pour utiliser celui de gmail (en acceptant cette appli dans Gmail) ?

merci
Thomas

**Comment by OsaAjani** [comment]
Salut,
pour l'instant l'envoi de mail se fait directement via la fonction mail() de php. Il faudrait configurer PHP en modifiant le fichier php.ini, soit pour utiliser le serveur SMTP de gmail directement si c'est possible, soit pour utiliser sendmail en local en configurant celui-ci pour qu'il utilise une serveur SMTP externe pour l'envoi, celui de Gmail.
