### ISSUE TITLE
parseSMS.sh

### ISSUE THREAD

**Issue by skitzoo** [RaspbianFrance/raspisms#144]
Bonjour,

J'ai un soucis avec le fichier parseSMS.sh à la ligne for i in `seq $SMS_MESSAGES` ; do

J'ai l'erreur -> seq: operande manquante car je suppose qu'il faut ajouter un paramètre mais je ne sais pas quoi mettre.

Avez vous une solution car ça bloque le script du coup

Merci

**Comment by OsaAjani** [comment]
Ce fichier est prévu pour être appelé par le daemon gammu-smsd. C'est lui qui est en charge de passer ce paramètre.
