### ISSUE TITLE
Erreur 404 lors du clic

### ISSUE THREAD

**Issue by Oliviercreativ** [RaspbianFrance/raspisms#149]
Bonsoir, 
J'ai refait une install suite à mon précédent message, j'ai bien tout remis en place ( gammu, gammu-smsd, python-gammu .... ) mais par contre quand je clique sur un lien ( une fois connecté ) ça m'affiche une erreur 404 : 
_Not Found
The requested URL was not found on this server._

Je pensais ça venait des url rewrite ... mais en activant le mod pour apache2, ça n'a pas changé.
Avez-vous une idée pour mettre les bons droits svp ?

Merci

**Comment by OsaAjani** [comment]
Salut, pour avoir de l'aide de la part des gens il faudrait que tu en dises un peu plus, version de RaspiSMS, URL sur laquelle tu as été redirigé, etc. Par ailleurs, pour un problème qui semble d'avantage relever de l'installation que du bug, tu trouveras potentiellement plus d'aide sur le forum (https://forum.raspberry-pi.fr) qu'ici.
