### ISSUE TITLE
Réception d'un SMS - Non disponible alors que tout fonctionne

### ISSUE THREAD

**Issue by FredMa01** [RaspbianFrance/raspisms#156]
Alors que l'installation d'un téléphone Gammu fonctionne parfaitement, je continue d'avoir des propriétés qui annoncent une indisponibilité.
C'est moins grave que le contraire  ;)
![image](https://user-images.githubusercontent.com/31782793/108856613-8939dd80-75ea-11eb-8d74-b1d2fb4c4526.png)

**Comment by OsaAjani** [comment]
C'est parfaitement normal, c'est la partie callbacks du tableau, laquelle indique les adresses à appeler pour signaler la réception ou le changement de statut d'un SMS à RaspiSMS.

Tu as donc "Non disponible." tout simplement parceque les téléphones gammu ne sont pas prévus pour recevoir ou envoyer des SMS par callback, mais plutôt directement en communiquant avec gammu.
