### ISSUE TITLE
Purge des statistiques  et messages

### ISSUE THREAD

**Issue by FredMa01** [RaspbianFrance/raspisms#161]
Une option qui pourrait être intéressante serait la purge des statistiques et donc des "Messages envoyés, reçus et non lus".

**Comment by OsaAjani** [comment]
Les statistiques sont faites à partir de la liste des messages envoyés et réçus, donc pour vider les stats il faudrait supprimer les messages envoyés et reçus. On reviens un peu sur la même chose que pour l'issue #158, à savoir qu'il faudrait rajouter la possibilité de sélectionner tous les messages envoyés et reçus d'un seul coup. Actuellement il est possible de les selectionner par groupe de 25 à coup de clic + Shift.

**Comment by FredMa01** [comment]
Parfait.
