### ISSUE TITLE
Le lien du repo n'est pas à jour

### ISSUE THREAD

**Issue by kartsims** [RaspbianFrance/raspisms#164]
http://raspisms.raspbian-france.fr/ ne fonctionne pas

**Comment by RaspbianFrance** [comment]
Merci de l'avoir signalé, il s'agissait de l'ancien site du projet, j'ai modifié le lien pour pointer vers le bon domaine. Normalement une redirection était en place pour pointer vers le nouveau site, mais avec l'incendie de OVH le serveur a changé d'IP et le changement DNS pour ce sous-domaine en particulier est passée entre les mail du filet ^^.
