### ISSUE TITLE
Instabilité notoire avec Gammu

### ISSUE THREAD

**Issue by walawa75** [RaspbianFrance/raspisms#170]
Que ce soit avec un dongle Huawei E220 ou avec un SIM800C USB (pas la bouse ignoble de SIM800L à bricoler soi même) on note un fonctionnement erratique à l'émission et à la réception. J'ai comme l'impression que gammu ne fonctionne pas bien du tout depuis stretch et que la version 2 de RaspiSMS sous Jessie tournait (et tourne toujours chez moi) comme une horloge.

Bref tout ça manque énormément de fiabilité en mode "gratuit" et c'est malheureux car le projet était beau.

**Comment by OsaAjani** [comment]
Bonjour,
nous ne sommes pas responsables des changements qui ont pu avoir lieu au sein de gammu et des paquets gammu pour Debian/Raspbian depuis Stretch, et je n'ai à vrai dire aucune certitude quand au fait de savoir si ceux-ci ont changé, et encore moins s'il fonctionnent mieux ou moins bien qu'avant. Si vous avez constaté des regressions ou des changements néfastes à la stabilité de gammu ou des paquets, je vous encourage à aller les signaler directement auprès des mainteneurs de gammu et des paquets Debian associés.

Maintenant, concernant RaspiSMS et la façon dont le logiciel s'interface avec Gammu, certains changements ont eu lieu depuis la version 2.0. Notamment, nous n'utilisons plus le démon gammu-smsd et passons directement via la ligne de commande de gammu pour l'envoi des SMS, et par un script python pour leur réception. Cela nous permet notamment d'utiliser plusieurs téléphones gammu beaucoup plus facilement.

Ces changements introduisent toutesfois quelques pré-requis : 
- Créer un et un seul fichier de configuration pour un et un seul téléphone, sans quoi des blocages surviennent entre les téléphones.
- Qu'aucun autre logiciel n'utilise gammu, notamment que le démon gammu-smsd ne soit pas installé/démarré.

Si vous voyez une erreur dans l'adaptateur raspsisms <-> gammu ou dans le script python, nous serons ravis de nous pencher dessus ou d'intégrer une pull request.

Tout ce que je peux vous conseiller c'est donc de faire l'installation de RaspiSMS sur une image neuve de Debian, de construire des fichiers de configuration différents pour chaque téléphone, en vous inspirant de [](https://documentation.raspisms.fr/users/adapters/gammu.html#exemple-de-fichier-de-configuration), et de vérifier que ces téléphones fonctionnent comme prévu directement avec gammu, en ligne de commande et sans passer par RaspiSMS, avant des les essayer dans RaspiSMS.

Quand au manque de fiabilité en mode gratuit, et bien tout ce que je peux que dire, c'est que RaspiSMS est bien plus fiable, robuste et puissant aujourd'hui qu'il ne l'était dans sa version 2 (laquelle est d'ailleurs toujours disponible dans les archives si vous ne souhaitez pas passer à la version 3), et qu'un logiciel n'est jamais plus fiable que la personne qui l'installe et le configure.

En attendant, cette issue ne signalant aucun problème précis ni élèments vérifiables et n'apportant pas propositions d'évolutions, je met permet de la clore.
