### ISSUE TITLE
Synology send SMS

### ISSUE THREAD

**Issue by melahel** [RaspbianFrance/raspisms#203]
I installed RaspiSMS on a Debian 10 that works well.
I don't succeed to send SMS with my Synology throw the tool. It works fine if I put directly the command line but never succeed to configure the Syno tool.
Does anyone already done it ?

Thank you

**Comment by Vikingfr** [comment]
You need to make a script to convert GET request from the Synology to POST request for the API. Look here: https://github.com/RaspbianFrance/raspisms/issues/201
