### ISSUE TITLE
raspisms et gammu-smsd

### ISSUE THREAD

**Issue by gblanchet** [RaspbianFrance/raspisms#206]
Bonjour,
j'ai installé raspisms sur un raspberrypi où tourne le daemon gammu-smsd.
Je dois passer la commande
sudo systemctl stop gammu-smsd 
pour pouvoir envoyer et recevoir des sms par raspisms.
Est-ce normal ?

**Comment by OsaAjani** [comment]
Cest parfaitement normal, ne RaspiSMS ne peux pas tourner avec gammu-smsd puisque le démon gammu rend gammu inaccessible pour RaspiSMS.
