### ISSUE TITLE
... (3 petits points) devant une variable PHP ? C'est normal ?

### ISSUE THREAD

**Issue by memento** [RaspbianFrance/RaspiSMS#22]
Bonjour,

J'ai pris la dernière version.
Quand j'essaye d'afficher des pages comme :
SMS => http://mon-site.fr/RaspiSMS/scheduleds/
>_ Commandes => http://mon-site.fr/RaspiSMS/commands/
Répertoire>Contacts => http://mon-site.fr/contacts
Répertoire>Groupes => http://mon-site.fr/groups
Utilisateurs => http://mon-site.fr/RaspiSMS/users/

J'ai ne page blanche.
Le log me dit par exemple :

```
Sep 21 13:28:48 rpi apache2: PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/www/RaspiSMS/controllers/commands.php on line 39
```
ou encore :

```
Sep 21 13:33:14 rpi apache2: PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/www/RaspiSMS/controllers/scheduleds.php on line 37
```

PHP ne supporte pas les 3 petits points ...

Par exemple, dans le fichier controllers/contacts.php, j'ai :
```php
public function delete($csrf, ...$ids)
```

Je ne connaissais pas les ... devant une variable. :)

**Comment by memento** [comment]
D'accord, l'opérateur ... est disponible à partir de la version 5.6 (et plus) de PHP
()
Sur mon raspbian je n'ai que la version 5.4.41

**Comment by memento** [comment]
En faisant une mise à jour de PHP 
```
sudo apt-get update && sudo apt-get install php5
```

Je n'ai pu passer qu'à la version : 
```
PHP 5.4.45-0
```

je vais compiler les sources du paquet php5 mais pour les utilisateurs lambdas qui ne pourront/voudront que lancer l'installation des paquets avec ___apt-get___, l'utilisation de cet opérateur ... n'est à mon avis pas judicieux.

**Comment by memento** [comment]
Ok, la mise à jour vers cette version de php obligera également à changer de version d'apache sachant que la mise à jour d'apache (2.2 vers 2.4) n'a pas la même façon de gérer les fichiers de conf, plus d'autres modifications de la configuration.
ça commence à faire beaucoup pour un opérateur, non ?

Quelqu'un a une astuce ? (un guru de php)

Bien à vous !

**Comment by memento** [comment]
Le fait de supprimer les ... ne semble pas perturber les contrôleurs.
J'espère que ça aidera quelqu'un !

**Comment by RaspbianFrance** [comment]
Salut, les "..." permettent de récupérer plusieurs variables.
Dans le cas présent cela est par exemple utile pour supprimer plusieurs contacts.
Je pense qu'il va effectivement falloir que nous trouvions une façon de gérer cela en restant dans une version < à 5.6 (même si c'est bien dommage).

Je pense qu'il devrait être possible d'utiliser les fonctions func_get_args(). 
C'est nettement moins élégant, mais plus rétro-compatible;
Je me penche sur la question dès maintenant.

**Comment by RaspbianFrance** [comment]
Le problème viens d'être corrigé.
La solution choisie est l’utilisation de la fonctions func_get_args.

**Comment by memento** [comment]
La modification est déjà dans le code ?

**Comment by RaspbianFrance** [comment]
Oui, nous avons mis à jour tout ça :)

2015-09-22 13:42 GMT+02:00 memento <notifications@github.com>:

**Comment by memento** [comment]
Merci !
Quel boulot vous faites !

**Comment by RaspbianFrance** [comment]
Il pleut tout le temps en charente en ce moment, faut bien s'occuper !

2015-09-22 14:48 GMT+02:00 memento <notifications@github.com>:
