### ISSUE TITLE
Dossier "connections" non présent dans /usr/share/raspisms

### ISSUE THREAD

**Issue by GBInformatics** [RaspbianFrance/raspisms#220]
Bonjour,
Je suis en train de mettre en place raspisms sur un rpi 3B+ sous bullseye 32bits.
Ce que j'ai réussi à faire : 
- Faire afficher la page d'authentification http://192.168.X.X/raspisms/
- Me connecter sur le compte via adresse.gmail@gmail.com et le mot de passe
          - J'ai du créer la base de données et l'utilisateur à la main avec mariadb car j'avais une erreur à cause du mot de 
          passe crypté (que j'ai remplacé par un nom crypté dans env.prod.php et phinx.yml) pour ensuite migrer la base de 
          données avec php vendor/bin/phinx migrate. Ca a fonctionné.
- Je peux désormais me connecter sur mon compte via le lien http://192.168.X.X/raspisms/.

A partir de là, je suis bloqué. J'ai la page "Not found The requested URL was not found on this server.
Apache/2.4.56 (Raspbian) Server at 192.168.X.X Port 80"

Selon le lien (http://192.168.X.X/raspisms/connections). Raspisms va dans le dossier "connections" pour se connecter mais je ne l'ai pas dans /usr/share/raspisms/.

Savez-vous où il se trouve ?

**Comment by vincent1890** [comment]
Bonjour avez vous suivi la procedure d'installation situé ici [https://raspisms.fr/download/](https://raspisms.fr/download/) ?

Il n'y a pas de dossier connections dans le dossier ou est installé RaspiSMS

**Comment by GBInformatics** [comment]
Je n'vais pas vu, autant pour moi.

Oui tout à fait j'ai suivi le tutoriel du lien.

**Comment by vincent1890** [comment]
> Je n'vais pas vu, autant pour moi.
> 
> Oui tout à fait j'ai suivi le tutoriel du lien.

Vous n'avez eu aucune erreur a l'installation ?

Vous pouvez tenter l'installation d'un deb NON officiellement sortie car cela n'est pas une release ! (A utiliser a vos risque et périls)
https://github.com/RaspbianFrance/raspisms-deb/blob/master/packages/latest.deb

Ou alors telecharger le git sur le Github localement pour mettre a jour l'installation

**Comment by GBInformatics** [comment]
Pourquoi pas en soit mais je ne voudrais pas tout perdre (ensuite) si j'arrive à l'installation. Est ce que vous vouslez que j'essaie votre installation sur une rapsberry pi chez moi ?

**Comment by GBInformatics** [comment]
Bponjour j'ai essayé avec docker. L'achitecture de ma raspberry n'est pas bonne.. je suis donc bloqué

**Comment by GBInformatics** [comment]
Bonjour il faut utiliser la version raspberry pi os 32 bits Legacy Lite
