### ISSUE TITLE
Taille du numéro de téléphone en base

### ISSUE THREAD

**Issue by Geminium** [RaspbianFrance/RaspiSMS#31]
La taille du numéro de téléphone en base est trop court.
Pour les préfixes en +262 (La Réunion) il faut 13 caractères et la base n'en prend que 12.

**Comment by RaspbianFrance** [comment]
Salut,
à un caractère prêt :/
Du coup pas sécurité nous modifions la base pour accepter 20 caractères. Comme ça, on est tranquilles pour un moment ;)

Nous allons mettre à jour les paquets ce week-end. En attendant, tu peux fixer ça en téléchargeant la dernière version du fichier "createDatabase.sql" et en supprimant/recréant la base avec le fichier.
