### ISSUE TITLE
Sauvegarde du paramètre:  Détection des URL dans les discussions

### ISSUE THREAD

**Issue by Geminium** [RaspbianFrance/RaspiSMS#32]
Le champs en base est : detect_url et le post se fait sur detection_url
Il y a donc une erreur à la sauvegarde.

**Comment by RaspbianFrance** [comment]
Merci du retour, c'est corrigé.
Nous allons refaire les paquet .deb et autres ce week-end. En attendant, tu peux fixer le problème en téléchargeant le fichier templates/settings/default.php
