### ISSUE TITLE
Bug - telephone mobile number

### ISSUE THREAD

**Issue by david-chiappetta** [RaspbianFrance/RaspiSMS#34]
Hi,
on database the max data insert of mobile number is 12, but in Italy the telephone number is for example +393331234567 all are 13 characters.
If I try to send SMS with RaspySMS the number is truncated like +39333123456

**Comment by RaspbianFrance** [comment]
Hi,
this issue was already report (and fixed on github). We will add this fix soon.
Anyway, thanks for your report.

**Comment by darKy123** [comment]
sorry for opening , can you say me how php i must edit to fixx the problem? I load actuellay  raspisms 2.0.deb without the fixx :( and i will fixx it (im in holidays) thanks
