### ISSUE TITLE
Erreur lors de la modification des réglages

### ISSUE THREAD

**Issue by clementcohen** [RaspbianFrance/raspisms#39]
paquet deb récupérer à l'instant
j'ai une erreur quand je veux sauvegarder  les réglages (Dashboard > Reglage) "Impossible de mettres les données à jours" 

est-il possible d'avoir des logs également dans l'interface ..?

**Comment by RaspbianFrance** [comment]
Salut,
nous ne parvenons pas à reproduire le problème.

Es-tu certains que tu as bien modifié la valeur et que tu as cliquer sur le bouton correspondant au champ modifié ?
