### ISSUE TITLE
Projet vidéo-surveillance

### ISSUE THREAD

**Issue by dmpvost** [RaspbianFrance/raspisms#40]
Bonjour,

Je viens de trouvé votre projet sur le net.
Je vais l'essayer dès ce soir.

Je travail sur un projet qui consiste à avoir un raspberry (ou ordinateur) sur un site isolé, (pas d'internet). C'est une sorte de "centre de notification" entre les événements et la distributions aux utilisateurs.

Je me demandais si RaspiSMS ne pourrait pas intégré:
- gestion d'une connexion 3G? ON/OFF en parrallèle du flux SMS de gammu? Il me semble qu'il y a deux canaux de communication. Je n'ai pas encore essayer la co-habitation.

Cela permettrait d'activé une connexion sortante de type SSH ou VPN via SMS.
La connexion doit venir du système car les connexions 3G sont comme dans un NAT de l'opérateur.

objectif -> transformer RaspiSMS en un outil de gestion à distance, ou de possibilité de management à distance

Je vais pas en dire plus pour le moment :)
A bientôt
Vost

**Comment by RaspbianFrance** [comment]
Bonjour,
RaspiSMS n'as pas du tout pour but de gérer des connexions 3G donc nous ne
comptons pas ajouter cette fonctionnalité.
Pour ce qui est d'activer une connexion à distance, actuellement tu peux
envoyer des SMS à RaspiSMS pour déclencher des scripts sur la Raspberry Pi,
ça pourrait correspondre un peu à ce que tu cherches.

Il vos mieux que tu gère la connexion 3G via un autre logiciel et que
RaspiSMS reste dédié à la partie SMS.

Cordialement,
Raspbian France
