### ISSUE TITLE
Statut des SMS envoyés via l'API web (GET)

### ISSUE THREAD

**Issue by sebecam2000** [RaspbianFrance/raspisms#42]
Bonjour,
- Dans le menu "Logs > SMS envoyés", les SMS envoyés via l'API web ont tous un statut "inconnu" si on envoi vers un numéro de type 0477123456 (le problème ne se pose pas si on utilise +32477123456). Tandis que les SMS envoyés via l'interface web ont des statuts corrects.
  J'utilse l'API web via la méthode get: http://ip/RaspiSMS/smsAPI/?email=admin@example.fr&password=admin&numbers=numero&text=test
- Dans les menus "Logs", un bouton "sélectionner tout" serait le bienvenu pour ne pas avoir à cliquer sur chacun des boutons.

La simplicité d'utilisation est remarquable, beau boulot!

**Comment by memento** [comment]
Bonjour,
Quand on envoi un SMS, il faut savoir que l'opérateur renvoie toujours un accusé avec un numéro de la forme +<indicatif pays><numéro sans le 0 devant>. Du coup, si le module envoie un SMS au numéro 0477123456, il ne recevra qu'un accusé pour le numéro +32477123456 et le module n'arrivera pas à faire la correspondance.
Le problème a été réglé pour les envois de SMS via l'interface web (ré-écriture du numéro 0477123456 vers +32477123456 avant l'envoi).
Pour l'envoie via l'API, peut-être que la même démarche de ré-écriture n'a pas été faite. C'est là qu'il faut chercher.

Je parlais de ce problème (ici)[https://github.com/RaspbianFrance/RaspiSMS/issues/23]
