### ISSUE TITLE
SMS envoyé plusieurs fois

### ISSUE THREAD

**Issue by max06200** [RaspbianFrance/raspisms#45]
Bonjour,

Lorsque j'envoie un SMS via RaspiSMS, celui-ci est envoyé 2, voir 3 fois de suite....

Auriez vous une idée?

Merci

**Comment by RaspbianFrance** [comment]
Salut,
vérifie la crontab de l'utilisateur root. Tu trouveras probablement des
lignes dupliquées.

2016-04-29 14:47 GMT+02:00 max06200 <notifications@github.com>:

**Comment by dam09fr** [comment]
Dans l'éventualité d'une double exécution du cron, ne serait-il pas possible de mettre en place un contrôle de la façon suivante, afin de sécuriser le fonctionnement : 

Dans le script du cron :
si le fichier "cron.pid" existe alors
-  si ce fichier contient un PID en cours d'exécution alors
-  -  exit (la tâche est en cours)
-  sinon
-  -  on supprime le fichier "cron.pid" (le processus s'est fermé anormalement)
-  finsi
finsi
on crée un fichier "cron.pid" dans lequel on place le PID du processus courant
(exécution normale du script ...)
on supprime le fichier "cron.pid" à la fin de l'exécution

**Comment by RaspbianFrance** [comment]
Ce serait effectivement une possibilité.
De toute façon, le mécanisme de cron risque d'être pas mal revu
prochainement sur RaspiSMS.
Nous aimerions bien faire un système plus proche d'un deamon ou quelque
chose comme ça.

**Comment by StephaneTy-Pro** [comment]
Bonjour,
J'ai le même problème mais il est complètement aléatoire (au début j'ai pensé qu'il s'agissait d'un problème :" d'ordre de saisie de champs" mais au final il semblerait que non)

Auriez vous des idées pour corriger le sujet en l'état (=>avec l'utilisation de cron)

D'avance merci

**Comment by memento** [comment]
Bonjour,
Pour vérifier la table cron, tu peux taper la commande suivante (en root) :

'''
crontab -e
'''

Et vérifier les lignes en double.
Tu dois normalement avoir quelque chose comme ça :

'''
* * * * * cd /var/www/RaspiSMS && /var/www/RaspiSMS/console.php -c parseReceivedSMS
* * * * * cd /var/www/RaspiSMS && /var/www/RaspiSMS/console.php -c sendScheduleds
'''

Une fois la vérification/édition terminée, comme sous l'éditeur nano, fais un Ctrl+x
Si tu as fait une modification, on te proposera te taper o pour sauvegarder ou n pour abandonner les modifications.

**Comment by StephaneTy-Pro** [comment]
Merci je vais regarder au prochain envoi

**Comment by Tindome** [comment]
@memento Tout s'explique j'avais les lignes que tu évoques mais 4fois j'ai tout viré pour n'en laisser que deux
Merci

**Comment by max06200** [comment]
Je reviens sur le sujet, car j'avais laissé tombé un moment, mais je retente. Alors je n'avais rien dans mon fichier Cron, j'ai donc mis les 2 ligne indiqué plus haut, mais cela ne change rien.

Lorsque j'envoie un sms depuis le dashboard, certaine fois il l'envoi bien une fois, et certaine fois 2, 3 voir 10 fois.

Une autre idée pour solutionner le problème?

**Comment by RaspbianFrance** [comment]
Salut,
étais-tu bien en mode root quand tu à lancer la commande crontab -e ?
Lance d’abord la commande "sudo -s", puis seulement après "crontab -e".

Cordialement,
Raspbian France

**Comment by memento** [comment]
@max06200 Salut, as-tu solutionné ton problème ?

**Comment by vincent1890** [comment]
J'ai le même problème dans **http://IP/RaspiSMS/sendeds/** je me retrouve avec deux ligne pour chaque message et donc une des deux en toujours en **statut Inconnu** et l'autre en délivré ce qui est logique car je reçois un seul SMS.

Et il y bien que 2 ligne dans le crontab
Si quelqu'un a trouver la solution je suis preneur.
