### ISSUE TITLE
Signal strength

### ISSUE THREAD

**Issue by sebecam2000** [RaspbianFrance/raspisms#46]
Il n'y a actuellement pas moyen de voir la force du signal, ce qui est embêtant lorsque certains sms ne sont pas envoyés à cause d'un signal trop faible.
Pour pallier ce problème, j'utilise la commande comgt qui me renvoit le résultat d'un AT+CSQ (à mettre en lien avec le tableau de http://m2msupport.net/m2msupport/atcsq-signal-quality/ ), et je vérifie le nombre de messages en attente dans l'outbox.
Est-il prévu d'intégrer un tel composant dans votre interface?

**Comment by tux-vador** [comment]
Je pense que cette demande est vraiment utile aussi

**Comment by memento** [comment]
Pareil. Je suis pour.

**Comment by RaspbianFrance** [comment]
Salut,
nous notons l'idée et nous essayerons d'ajouter cette fonctionnalité dans
la prochaine version !

2016-06-01 23:45 GMT+02:00 memento <notifications@github.com>:
