### ISSUE TITLE
discussion not loaded and no pages

### ISSUE THREAD

**Issue by darKy123** [RaspbianFrance/raspisms#54]
I have write with my best friend 250 sms and raspisms is not loading the discussion, i see only the loading image but no content.

And i see only few sms and no pageable scrolling .. old sms are not shown.

**Comment by meXxmasteR** [comment]
me too :/
Same Problem with 1000 or more sms.

**Comment by meXxmasteR** [comment]
It's by you the same @darKy123 ?
http://www0.xup.in/exec/ximg.php?fid=20071521
