### ISSUE TITLE
Envoyer des SMS aux numéros spéciaux (Numéros Courts)

### ISSUE THREAD

**Issue by btronquo** [RaspbianFrance/raspisms#60]
Bonjour, 

Tout d'abord je tenais à vous féliciter pour la qualité de votre gestion RaspiSMS, c'est un outil vraiment au top !

Bossant pour une grosse boite de médias TV, j'ai créée un interface de control et d'envois de SMS sur plusieurs raspberry (et donc opérateurs) qui sra prochainement en open source .. 
Et je souhaite envoyer des SMS aux numéros courts

Ma question est donc: 
Est-il possible d'envoyer un sms à un numéro court ? (j'ai essayé, cela ne fonctionne pas en mettant le numéro court ni en rajoutant un "+"..  via l'API) 
Je ne trouve pas la commande gammu pour les numéros courts mais seulement pour les numéros normaux.. (sudo gammu sendsms TEXT 81212 -text "Test")

Avez vous une astuce pour faire en sorte que cela fonctionne ? 
Si oui, je me propose d'ajouter la fonctionnalité sur votre outil déjà super complet :)

@+

**Comment by memento** [comment]
Bonjour,

La commande gammu pour envoyer un SMS est la suivante :
```
echo "Texte du message" | gammu-smsd-inject TEXT NUMERO_TELEPHONE
```
NUMERO_TELEPHONE peut être au format national (ex: 0612345678) ou au format international ( ex: +33612345678)

Tu peux déjà faire tes tests avec cette commande.

Bonne soirée !
