### ISSUE TITLE
contenu des sms reçu  = pending

### ISSUE THREAD

**Issue by Blacksly** [RaspbianFrance/raspisms#66]
Salut a tous! 

Petite question, se recois certain sms avec pour contenue pending, a quoi est-ce du ? 
Merci

**Comment by RaspbianFrance** [comment]
Salut,
il faudrait regarder du coté de la doc de gammu.

Cordialement,
Raspbian France

2016-12-12 13:45 GMT+01:00 Blacksly <notifications@github.com>:

**Comment by memento** [comment]
Bonsoir, J'ai déjà eu ce cas.
Les SMS reçus avec le texte "pending" concernent certains opérateurs comme orange et ses sous-traitants comme Coriolis telecom.
Cela veut tout simplement dire que le SMS est en attente de livraison.
Cela ne sert à rien.
On pourrait imaginer un système de filtrage au moment de lire les SMS reçus.
On peut aussi imaginer un encart en plus dans l'interface d'administration pour ajouter des masques de filtrage.

**Comment by Blacksly** [comment]
hello ! punaise, j'ai pas vu ton commentaire depuis tout ce temps ... en tout cas merci pour l'info. 
Personnellement j'ai fais un truc très sale mais qui fonctionne, un cron qui supprime les sms "pending" ... en attendant de me remettre plus dans le code ^^
