### ISSUE TITLE
Vitesse d'envoi de SMS

### ISSUE THREAD

**Issue by ghayoz** [RaspbianFrance/raspisms#67]
Bonjour,
J'essaie d'envoyer des SMS d'alertes lors de problèmes. Dans ce cadre-là, j'aimerais envoyer des SMS à 50 personnes le plus rapidement possible. 
J'utilise l'API REST pour cela. C'est très rapide pour accepter la demande d'envoi, mais cela prend beaucoup de temps pour les livrer. Est-ce qu'il y a moyen d'accélérer cela? J'ai fais un test pour 100 et ça nécessite plus de 10 minutes...

Merci d’avance.

Guillaume

**Comment by extrablind** [comment]
Tu peux sans doute faire des tests avec gammu directement via et une bonne boucle en bash et injecter la date dans le corps du message pour savoir précisément ou tu en est :
`gammu-smsd-inject TEXT 0612345678 -text "testing 001 ...002... "`

Si c'est plus rapide, c'est que le goulot d'étranglement se situe chez RpiSms. Php devrait normalement ralentir le temps d'execution mais on devrait à peine le sentir.
