### ISSUE TITLE
Utiliser le code source de RaspiSMS

### ISSUE THREAD

**Issue by Ayabadsir** [RaspbianFrance/raspisms#69]
Bonjour,
j'ai lu la documentation de RasiSMS et je trouve votre travail très intéressant. Etant nouvelle dans le domaine de la programmation je cherche à reconstituer l'application en local puis-je avoir des pistes. 
Merci

**Comment by RaspbianFrance** [comment]
Bonjour,
Tu peux trouver toutes les sources sur le github du projet ->
https://github.com/RaspbianFrance/RaspiSMS

**Comment by extrablind** [comment]
@Tichinfopro 
RaspiSMS est basé sur du code MVC maison qui constitue un petit framework. Il faut donc que tu apprenne d'abord ce qu'est le MVC (Model View Controller) tu pourras ainsi t'y retrouver mieux dans le code. Va sur Open Classroom pour apprendre, par exemple.

**Comment by Tichinfopro** [comment]
Merci. je l'ai fais et j'ai compris. Merci bien
