### ISSUE TITLE
Envois multiples

### ISSUE THREAD

**Issue by Mafraysse** [RaspbianFrance/RaspiSMS#70]
Bonjour,

Pour une raison inconnue, des sms partent en double, voir triple...

Si quelqu'un a la solution... 
Merci

**Comment by RaspbianFrance** [comment]
Salut,
le problème viens très probablement de la présence de lignes dupliquées dans la crontab. Connectes toi en SSH sur la Raspberry Pi, et édites la crontab avec la commande `sudo crontab -e`. Tu trouveras probablement des lignes dupliquées, supprime les jusqu'à ne plus avoir qu'une seule ligne puis redémarre la raspberry pi.

**Comment by Mafraysse** [comment]
Bien joué ! Merci
