### ISSUE TITLE
statut toujours inconnu

### ISSUE THREAD

**Issue by llimz** [RaspbianFrance/raspisms#74]
Bonjour,

Le statut de l'envoi de mes SMS est toujours "inconnu". Les SMS sont envoyées depuis l'interface web et les numéros sont écrits avec +336 etc...  Les SMS sont bien reçus. Voici ci-dessous mon gammu-smsdrc pour vérification. 

Dans mon crontab (root) j'ai ça

`* * * * * cd /var/www/html/RaspiSMS && /var/www/html/RaspiSMS/console.php -c parseReceivedSMS
* * * * * cd /var/www/html/RaspiSMS && /var/www/html/RaspiSMS/console.php -c sendScheduleds`

Que puis-je vérifier d'autre? Merci d'avance. 

`[gammu]
GammuCoding = utf8
GammuLoc = fr_FR.UTF8
device = /dev/ttyUSB0
name = Phone on USB serial port Qualcomm__Incorporated Qualcomm_CDMA_Technologies_MSM
connection = at

[gammu1]
GammuCoding = utf8
GammuLoc = fr_FR.UTF8
device = /dev/ttyUSB1
name = Phone on USB serial port Qualcomm__Incorporated Qualcomm_CDMA_Technologies_MSM
connection = at

[gammu2]
GammuCoding = utf8
GammuLoc = fr_FR.UTF8
device = /dev/ttyUSB2
name = Phone on USB serial port Qualcomm__Incorporated Qualcomm_CDMA_Technologies_MSM
connection = at

[gammu3]
GammuCoding = utf8
GammuLoc = fr_FR.UTF8
device = /dev/ttyUSB3
name = Phone on USB serial port Qualcomm__Incorporated Qualcomm_CDMA_Technologies_MSM
connection = at

[smsd]
service = files
logfile = syslog
debuglevel = 0
RunOnReceive = /var/www/html/RaspiSMS/parseSMS.sh
inboxpath = /var/spool/gammu/inbox/
outboxpath = /var/spool/gammu/outbox/
sentsmspath = /var/spool/gammu/sent/
errorsmspath = /var/spool/gammu/error/`

Jimmy

**Comment by Ulrick17** [comment]
Bonjour llimz

As-tu résolu ton problème car j'ai le meme
