### ISSUE TITLE
probleme d'affichage SMS recu

### ISSUE THREAD

**Issue by walmins** [RaspbianFrance/raspisms#75]
Bonjour,
je n'arrive pas a afficher les messages reçu.
J'ai toujours cette erreur: "/srv/RaspiSMS/receiveds/popup" failed (2: No such file or directory),

J'utilise nginx avec un raspberry.

Merci

**Comment by meXxmasteR** [comment]
No standart path .. please user only RaspiSMS without other directorys.
like /var/www/RaspiSMS not /var/www/srv/RaspiSMS
