### ISSUE TITLE
Inverser l'ordre des messages dans les conversations et faire une requête ajax pour charger les messages plus anciens

### ISSUE THREAD

**Issue by extrablind** [RaspbianFrance/raspisms#80]
Il parait plus logique que les derniers messages apparaissent en premier et qu'il ne faille pas scroller pour les atteindre. 
De plus, rien ne sert de charger inutilement les premiers messages une requête ajax peut s'en charger à l'évènement scroll.

Florian

**Comment by meXxmasteR** [comment]
Thanks im not alone :( have you an idea to fix this?
Idea: Not load alle message's load 20 - 50 and then make a facebook like loading - when scroll up then load more one's.

**Comment by extrablind** [comment]
Yes, that's it : ajax requests on scroll and loading only firsts items could do the trick.

It's a priority enhancement in my opinion

**Comment by jhillairet** [comment]
Une facon simple d'inverser l'ordre des messages (du plus récent au plus ancien), est de modifier la fonction `getmessages()` qui se trouve dans le fichier `templates/discussions/show.php`, en modifiant : 

`$.each(data.messages, function(key, message) {`
en
`$.each(data.messages.reverse(), function(key, message) {`

**Comment by meXxmasteR** [comment]
Any fix the Problem or can give me tipps to fix it?

One User have 500 SMS in Discussion but its loading and loading.
