### ISSUE TITLE
RaspiSMS Impossible d'envoyer un sms à un "groups"

### ISSUE THREAD

**Issue by Samuel31400** [RaspbianFrance/raspisms#82]
Bonjour,

Je souhaiterai envoyer un sms à un groupe (plusieurs numéros de tel) qui ont été préalablement enregistrés dans RaspiSMS. Le problème est que le sms est envoyé uniquement au "numbers" et pas aux "groups".

Auriez vous une idée?  Voici ma ligne de command: 

curl -g http://127.0.0.1/RaspiSMS/smsAPI/&email=XXXXX@XX.com\&password=XXXXX\&numbers=XXXXXXXXXX\&groups[]=XXXXXX\&text=ca%20fonctionne

Merci pour votre aide

**Comment by RaspbianFrance** [comment]
Salut, l'url me semble un peu étrange, il devrais, je pense, y avoir un
?email plutot que &email.
Par contre, essaye de télécharger la dernière version depuis le github et
vois si ça ne résous pas le problème.
