### ISSUE TITLE
Change favicon state when receiving new SMS

### ISSUE THREAD

**Issue by extrablind** [RaspbianFrance/raspisms#88]
Hi, 
When receiving a new sms or when sms are pending reading; this could be interesting to change the favicon to tell user that there are SMS that need to be readed.

**Comment by RaspbianFrance** [comment]
Such a great idea, adding it to my personnal "Todo when i while finally
work on that !".

2017-09-04 23:59 GMT+02:00 extrablind <notifications@github.com>:
