### ISSUE TITLE
Réception d'un SMS de commande

### ISSUE THREAD

**Issue by GGSAS89** [RaspbianFrance/raspisms#91]
Bonjour,
J'ai une question au sujet des commandes qu'on peut exécuter à la réception d'un SMS, j'ai pas encore regardé en profondeur, mais j'ai fait un petit test rapide en bash, ça fonctionne parfaitement, mais je voudrais savoir si on peut récupérer le numéro de l'appelant, pour éventuellement lui répondre par SMS.

Est-il donné en paramètre au script exécuté? si oui de quelle façon?

A vous lire,
Cordialement,

Edit: bon, j'ai fait un test avec bash et un 'set > /tmp/set.log' pour voir, aucune variable initialisée avec un numéro quelconque, j'ai un peu cherché et j'ai modifié internalConsole.php, la ligne 365:

`exec("export SMS_FROM=$send_by; $command");`

comme ça je peut récupérer l'expéditeur si besoin.

**Comment by OsaAjani** [comment]
Nop, il me semble que le numéro n'est pas passé (mais c'est facilement possible en modifiant un peu le script php qui exécute les commandes pour passer à la fin de celles-ci un argument avec le numéro duquel vient le SMS).

----- Mail original -----
De: "Guillaumaud" <notifications@github.com>
À: "RaspbianFrance/RaspiSMS" <RaspiSMS@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Envoyé: Jeudi 16 Novembre 2017 09:07:45
Objet: [RaspbianFrance/RaspiSMS] Réception d'un SMS de commande (#91)



Bonjour, 
J'ai une question au sujet des commandes qu'on peut exécuter à la réception d'un SMS, j'ai pas encore regardé en profondeur, mais j'ai fait un petit test rapide en bash, ça fonctionne parfaitement, mais je voudrais savoir si on peut récupérer le numéro de l'appelant, pour éventuellement lui répondre par SMS. 

Est-il donné en paramètre au script exécuté? si oui de quelle façon? 

A vous lire, 
Cordialement,
