### ISSUE TITLE
Problèmes d'envoi d'un sms

### ISSUE THREAD

**Issue by Nems27** [RaspbianFrance/RaspiSMS#94]
Salut ,

Je rencontre un problème concernant l'envoi d'un sms
😦 … Lorsque je lance cette commande dans la console ' curl -g http://sms/RaspiSMS/smsAPI/?email=XXX@XXX.fr\&password=XXXXX\&numbers=06XXXXXXXX\&contacts=toto\&groups[]=groupe\&groups[]=test\&text=TestMultiGroupe ' Seul “numbers” reçoit le message mais le contact et les groupes non… Avez-vous des idées?

Merci d’avance de votre aide.

**Comment by pguillaumaud** [comment]
Bonjour,
J'ai rencontré le même souci, la réponse est la:
https://github.com/RaspbianFrance/RaspiSMS/issues/89

**Comment by Nems27** [comment]
@pguillaumaud D'accord merci beaucoup je vais regarder ca

**Comment by Nems27** [comment]
Merci beaucoup @pguillaumaud , pour les futurs personnes qui auront  ce problème, vous pouvez simplement récupérer le fichier smsAPI.php

**Comment by Blamo27** [comment]
@Nems27 Merci
