### ISSUE TITLE
Missing word in path

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [RaspbianFrance/raspisms#96]
I had a problem receiving a sms :

Jan 10 16:09:55 raspberrypi gammu-smsd[3012]: Starting run on receive: ```
/var/www/html/RaspiSMS/parseSMS.sh IN20180110_160944_00_+33650619536_00.txt
Jan 10 16:09:55 raspberrypi gammu-smsd[786]: Process failed with exit status 2
Jan 10 16:09:55 raspberrypi gammu-smsd[786]: Subprocess output: /var/www/html/RaspiSMS/parseSMS.sh: 14: /var/www/html/RaspiSMS/parseSMS.sh: cannot create /var/www/RaspiSMS/receiveds/20180110160955203366764.txt: Directory nonexisten
```

I realised that the right path should be : var/www/html/RaspiSMS/receiveds/

With last version of Raspbian.
If change the line in /var/www/html/RaspiSMS/parseSMS.sh
`echo "$sms" >> /var/www/RaspiSMS/receiveds/"$date".txt`
with : "$sms" >> /var/www/html/RaspiSMS/receiveds/"$date".txt

And the text file is created when receiving sms

**Comment by LaurentThiol** [comment]
I confirm the issue for me too
